<?php

namespace James\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	/**
     *
     * @access public
     * @param Proposal $proposal
     * @param \DateTime $time
     */
    public function searchUsers($terms=null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
  		  $qb->select('u')
           ->from('James\UserBundle\Entity\User', 'u')
           ->where('1=1'); //Dummy statement

        if(isset($terms['id']) && $terms['id'] != ''){
          $qb->andWhere('u.id = :id')
             ->setParameter(':id', $terms['id']);
        }

        if(isset($terms['lastName']) && $terms['lastName'] != ''){
          $qb->andWhere('u.lastName LIKE :lastName')
             ->setParameter(':lastName', '%' . $terms['lastName'] . '%');
        }

        if(isset($terms['email']) && $terms['email'] != ''){
          $qb->andWhere('u.email = :email')
             ->setParameter(':email', $terms['email']);
        }

        $user_query = $qb->getQuery();

        try {
            return $user_query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
