user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"